events { worker_connections 1024;
}
http {
    upstream novamart_app {
        server app:3000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://novamart_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}